# Generated by Django 4.2.7 on 2023-12-21 02:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vedassist", "0002_alter_user_email_alter_user_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="user",
        ),
    ]
