# Generated by Django 5.0 on 2023-12-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vedassist", "0003_remove_medicine_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="door_no",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="pincode",
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="street",
            field=models.CharField(default="", max_length=100),
        ),
    ]
